// Auto-generated by news_llm_generator.py
// Last updated: 2025-11-03 12:45:19

// Ticker text (pre-formatted with separators - DEPRECATED, use TICKER_OBJECTS)
window.TICKER_TEXT = `NASA ROCKET LAUNCHES NEW SATELLITE • AMAZON EXPANDS SUSTAINABLE SHIPPING • MICROSOFT RELEASES NEW EDUCATION TOOL • DISNEY THEME PARK EXPANSION UNDERWAY • GOOGLE ANNOUNCES NEW SCHOLARSHIP PROGRAM • APPLE WATCH SERIES 8 RELEASED • SPACEX STARLINK INTERNET SERVICE LAUNCHED • NATIONAL GEOGRAPHIC PARTNERS WITH NASA • FACEBOOK INTRODUCES NEW MENTAL HEALTH TOOL • IBM UNVEILS NEW QUANTUM COMPUTER • SONY RELEASES NEW PLAYSTATION CONSOLE • SPACE X DRAGON CAPSULE SUCCESSFULLY LANDS • NVIDIA LAUNCHES NEW GRAPHICS CARD • AMAZON RAINFORREST CONSERVATION EFFORTS • CISCO SYSTEMS UNVEILS NEW CYBERSECURITY TOOL • INTEL RELEASES NEW PROCESSOR WITH AI CAPABILITIES • HP INC. LAUNCHES NEW SUSTAINABLE PRINTING SOLUTION • MICROSOFT AZURE EXPANDS CLOUD SERVICES • DELL TECHNOLOGIES UNVEILS NEW LAPTOP LINE • ORACLE CORPORATION RELEASES NEW DATABASE SYSTEM • AT&T UNVEILS NEW 5G NETWORK EXPANSION • VERIZON COMMUNICATIONS LAUNCHES NEW EDUCATION PLATFORM • EBAY EXPANDS SUSTAINABLE SHOPPING INITIATIVE • `;

// Ticker items as objects with headline and detail
window.TICKER_OBJECTS = [
  {
    "headline": "NASA ROCKET LAUNCHES NEW SATELLITE",
    "detail": "US space agency successfully deploys advanced weather satellite from Florida launchpad to improve forecasting accuracy nationwide"
  },
  {
    "headline": "AMAZON EXPANDS SUSTAINABLE SHIPPING",
    "detail": "E-commerce giant introduces eco-friendly packaging and carbon offset program for all deliveries worldwide, reducing waste by 50%"
  },
  {
    "headline": "MICROSOFT RELEASES NEW EDUCATION TOOL",
    "detail": "Tech company launches free online learning platform with interactive lessons and virtual labs for students in over 100 countries"
  },
  {
    "headline": "DISNEY THEME PARK EXPANSION UNDERWAY",
    "detail": "Entertainment giant breaks ground on new $1 billion theme park in California, creating 10,000 jobs and featuring immersive experiences"
  },
  {
    "headline": "GOOGLE ANNOUNCES NEW SCHOLARSHIP PROGRAM",
    "detail": "Tech company offers $10 million in scholarships to underrepresented students in STEM fields, promoting diversity and inclusion"
  },
  {
    "headline": "APPLE WATCH SERIES 8 RELEASED",
    "detail": "Tech giant unveils latest smartwatch with advanced health monitoring and fitness tracking features, available in 40 countries"
  },
  {
    "headline": "SPACEX STARLINK INTERNET SERVICE LAUNCHED",
    "detail": "Elon Musk's aerospace company introduces high-speed satellite internet for remote communities, bridging digital divide"
  },
  {
    "headline": "NATIONAL GEOGRAPHIC PARTNERS WITH NASA",
    "detail": "Media company collaborates with US space agency on new documentary series exploring space exploration and astronomy"
  },
  {
    "headline": "FACEBOOK INTRODUCES NEW MENTAL HEALTH TOOL",
    "detail": "Social media platform launches AI-powered mental health resource with personalized support and crisis intervention"
  },
  {
    "headline": "IBM UNVEILS NEW QUANTUM COMPUTER",
    "detail": "Tech company introduces advanced quantum computing system with 53 qubits, accelerating scientific research and discovery"
  },
  {
    "headline": "SONY RELEASES NEW PLAYSTATION CONSOLE",
    "detail": "Gaming giant launches next-generation console with enhanced graphics and virtual reality capabilities"
  },
  {
    "headline": "SPACE X DRAGON CAPSULE SUCCESSFULLY LANDS",
    "detail": "Elon Musk's aerospace company achieves milestone with reusable spacecraft, paving way for future crewed missions"
  },
  {
    "headline": "NVIDIA LAUNCHES NEW GRAPHICS CARD",
    "detail": "Tech company introduces advanced graphics processing unit with artificial intelligence capabilities, enhancing gaming and video production"
  },
  {
    "headline": "AMAZON RAINFORREST CONSERVATION EFFORTS",
    "detail": "E-commerce giant partners with environmental organizations to protect 1 million acres of rainforest, promoting biodiversity and sustainability"
  },
  {
    "headline": "CISCO SYSTEMS UNVEILS NEW CYBERSECURITY TOOL",
    "detail": "Tech company launches advanced threat detection system with AI-powered analytics, protecting businesses from cyber threats"
  },
  {
    "headline": "INTEL RELEASES NEW PROCESSOR WITH AI CAPABILITIES",
    "detail": "Tech company introduces advanced central processing unit with integrated artificial intelligence, enhancing performance and efficiency"
  },
  {
    "headline": "HP INC. LAUNCHES NEW SUSTAINABLE PRINTING SOLUTION",
    "detail": "Tech company introduces eco-friendly printing technology with recycled materials and reduced waste, promoting environmental sustainability"
  },
  {
    "headline": "MICROSOFT AZURE EXPANDS CLOUD SERVICES",
    "detail": "Tech company launches new cloud computing platform with advanced security and AI capabilities, supporting businesses worldwide"
  },
  {
    "headline": "DELL TECHNOLOGIES UNVEILS NEW LAPTOP LINE",
    "detail": "Tech company introduces latest laptop series with enhanced performance, battery life, and sustainability features"
  },
  {
    "headline": "ORACLE CORPORATION RELEASES NEW DATABASE SYSTEM",
    "detail": "Tech company launches advanced database management system with AI-powered analytics, supporting businesses and organizations"
  },
  {
    "headline": "AT&T UNVEILS NEW 5G NETWORK EXPANSION",
    "detail": "Telecommunications company introduces high-speed 5G network in 20 new cities, enhancing mobile connectivity and coverage"
  },
  {
    "headline": "VERIZON COMMUNICATIONS LAUNCHES NEW EDUCATION PLATFORM",
    "detail": "Telecommunications company introduces online learning platform with interactive lessons and virtual labs for students"
  },
  {
    "headline": "EBAY EXPANDS SUSTAINABLE SHOPPING INITIATIVE",
    "detail": "E-commerce company introduces new program promoting eco-friendly products, reducing waste, and supporting environmental sustainability"
  }
];

// Breaking news headlines (array)
window.TICKER_ITEMS = [
  "TESLA UNVEILS NEW ELECTRIC CAR MODEL",
  "GOOGLE DEVELOPS LIFE-SAVING MEDICAL TOOL",
  "AMAZON EXPANDS GLOBAL REACH TODAY",
  "SPACEX LAUNCHES NEW SATELLITE SYSTEM",
  "NETFLIX PRODUCES RECORD NUMBER SHOWS",
  "APPLE CREATES REVOLUTIONARY NEW TABLET",
  "FACEBOOK INTRODUCES NEW SAFETY FEATURES",
  "NASA DISCOVERS NEW PLANETARY SYSTEM",
  "DISNEY RELEASES NEW ANIMATED FILM",
  "IBM DEVELOPS ARTIFICIAL INTELLIGENCE BREAKTHROUGH",
  "SPACE X BUILDING NEW ROCKET FACILITY",
  "YOUTUBE REACHES ONE BILLION USERS",
  "SONY UNVEILS NEW VIRTUAL REALITY SYSTEM",
  "NVIDIA DEVELOPS FASTER COMPUTER CHIPS",
  "AMAZON OPENS NEW SUSTAINABLE HEADQUARTERS",
  "GOOGLE MAPS EXPANDS GLOBAL COVERAGE",
  "MICROSOFT PARTNERS WITH TOP EDUCATORS",
  "TESLA EXPANDS ELECTRIC CAR CHARGING NETWORK",
  "NASA SENDS NEW SPACECRAFT TO MARS"
];

// Timestamp
window.TICKER_UPDATED_AT = '2025-11-03T12:45:19.885093';
